kafka:
  servers: "10.251.35.201:9092,10.251.35.202:9092,10.251.35.203:9092,10.251.35.204:9092,10.251.35.205:9092"
  topic: "bi_mdm_product_picture"
  consumer_name: "bdc.product_img_vector"

milvus:
  host: 10.251.37.251
  port: 19531
  user: bdc
  password: um5R3UYhgbv6L4Ri
  database: bdc_image_vectors
  collection: bi_mdm_product_picture

minio:
  endpoint: 10.251.37.248:7778
  access_key: dlink_write
  secret_key: qzw4Mh3tH4RSYpMo
  bucket_name: ods-ps

image_server:
  server_prefix: "https://retailp2.bellecdn.com/"

